// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAG_wU-Ef0bTr3IbLQdAgw8Ks6IFURbYaI',
    appId: '1:154251288758:web:fe064997a1542da426c617',
    messagingSenderId: '154251288758',
    projectId: 'fasum-main',
    authDomain: 'fasum-main.firebaseapp.com',
    storageBucket: 'fasum-main.firebasestorage.app',
    measurementId: 'G-B72VF12V1H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD3znZ0-v5KG_f5Zr-nxUH1Uybm36YnR44',
    appId: '1:154251288758:android:84b8e1e457f7a4eb26c617',
    messagingSenderId: '154251288758',
    projectId: 'fasum-main',
    storageBucket: 'fasum-main.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCTSfzNPxoZBFbVBEiBWv7kfzcAzzybWVs',
    appId: '1:154251288758:ios:ad8e4ee513b1b22c26c617',
    messagingSenderId: '154251288758',
    projectId: 'fasum-main',
    storageBucket: 'fasum-main.firebasestorage.app',
    iosBundleId: 'com.example.fasum',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCTSfzNPxoZBFbVBEiBWv7kfzcAzzybWVs',
    appId: '1:154251288758:ios:ad8e4ee513b1b22c26c617',
    messagingSenderId: '154251288758',
    projectId: 'fasum-main',
    storageBucket: 'fasum-main.firebasestorage.app',
    iosBundleId: 'com.example.fasum',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAG_wU-Ef0bTr3IbLQdAgw8Ks6IFURbYaI',
    appId: '1:154251288758:web:3f76b1eff7fb75b526c617',
    messagingSenderId: '154251288758',
    projectId: 'fasum-main',
    authDomain: 'fasum-main.firebaseapp.com',
    storageBucket: 'fasum-main.firebasestorage.app',
    measurementId: 'G-H9TXZPF4NW',
  );
}
